#!/bin/bash
# author: Karol Dudek <karoiz@sli.pl>

###############################################

#DEVICE=/dev/sda
DEVICE=/dev/nvme0n1

DIR=$(dirname $0)
#DIR=/run/archiso/bootmnt
#DIR=/mnt/netdisk/restore/home_desktop

###############################################

echo "-- Image compatibility verification with computer"

IMAGE_UUID=$(cat $DIR/info/uuid)
COMPUTER_UUID=$(cat /sys/class/dmi/id/product_uuid)

echo "Image    UUID : $IMAGE_UUID"
echo "Computer UUID : $COMPUTER_UUID"

if [ "$IMAGE_UUID" = "$COMPUTER_UUID" ]
then
  echo "The restore copy matches your computer"
else
  echo "The restore copy NOT matches your computer"
  exit 1
fi

if [ -b $DEVICE ]
then
  echo "-- Found disk $DEVICE"
else
  echo "-- Disk not found $DEVICE"
  exit 2
fi

sleep 2

if [ $(ls $DEVICE* | wc -l) -eq 1 ]
then
  echo "-- Restoring system on clean disk"
  sgdisk -Z $DEVICE
  dd if=$DIR/disk/table of=$DEVICE
  sgdisk -e $DEVICE
else
  echo "-- Restoring system on old disk"
fi

sleep 5

for PART in $(ls -I table $DIR/disk | cut -d. -f1 | uniq)
do
  PARTITION=$(dirname $DEVICE)/$PART
  FILEPATH=$(ls $DIR/disk/$PART* | head -n 1)
  TYPE=$(basename $FILEPATH | cut -d. -f2)
  ARCHIVER=$(basename $FILEPATH | cut -d. -f3)

  echo "-- Restoring copy of $PARTITION partition from $FILEPATH"

  if [ "stream" = "$TYPE" ]
  then
    # workaround because partclone.imager v0.3.12 - image size always zero / segmentation fault
    cat $DIR/disk/$PART.$TYPE.* | $ARCHIVER -cd > $PARTITION
  else
    cat $DIR/disk/$PART.$TYPE.* | $ARCHIVER -cd | partclone.$TYPE -r -o $PARTITION
  fi
done

echo "---------------------------------------------------"

sync

if [ -n "$(grep /dev/sr0 /proc/mounts)" ]
then
  eject -m cdrom
fi

sleep 2

echo "-- Remove disc from drive and press ENTER to restart your computer"

read

echo 1 > /proc/sys/kernel/sysrq
echo b > /proc/sysrq-trigger
