#!/bin/bash -e
# author: Karol Dudek <karoiz@sli.pl>

###############################################

#DEVICE=/dev/sda
DEVICE=/dev/nvme0n1

DIR=$(dirname $0)
#DIR=/mnt/netdisk/restore/home_desktop

#ARCHIVER=lzop    # low compression (very fast compression)
#ARCHIVER=lz4     # low compression (very fast decompression)
#ARCHIVER=gzip    # normal compression
ARCHIVER=xz      # high compression

###############################################

export XZ_DEFAULTS='--threads=0'

mkdir -p $DIR/info $DIR/disk

echo "-- Saving computer specification.."
cat /sys/class/dmi/id/product_uuid > $DIR/info/uuid
dmidecode -t0 > $DIR/info/bios
dmidecode -t1 > $DIR/info/system
lscpu > $DIR/info/cpu
hwinfo --netcard | grep -E 'controller|Model:|Permanent HW Address:' > $DIR/info/netcard
sgdisk -p $DEVICE > $DIR/info/disk
cat $DIR/info/system

echo "-- Creating copy of partition table.."
dd if=$DEVICE of=$DIR/disk/table bs=512 count=34

for PARTITION in $(ls $DEVICE?*)
do
  TYPE=$(blkid -s TYPE -o value $PARTITION)
  if [ ! -x /usr/bin/partclone.$TYPE ]
  then
    TYPE=imager
  fi

  echo "-- Creating copy of $PARTITION partition.."
  partclone.$TYPE -c -s $PARTITION | $ARCHIVER -c | split -d -b1G - $DIR/disk/$(basename $PARTITION).$TYPE.$ARCHIVER.
done

echo "-- Backup complete."
