#!/bin/bash
# author: Karol Dudek <karoiz@sli.pl>

###############################################

#DEVICE=/dev/sda
DEVICE=/dev/nvme0n1

DIR=$(dirname $0)
#DIR=/mnt/netdisk/restore/home_desktop

#ARCHIVER=lzop    # low compression (very fast compression)
#ARCHIVER=lz4     # low compression (very fast decompression)
#ARCHIVER=gzip    # normal compression
ARCHIVER=xz      # high compression

###############################################

export XZ_DEFAULTS='--threads=0'

mkdir -p $DIR/disk

echo "-- Saving computer specification.."
lscpu > $DIR/cpu.info
grep -h -v 00:00:00:00:00:00 /sys/class/net/enp*/address | sort -u > $DIR/mac.info
sgdisk -p $DEVICE > $DIR/disk.info

echo "-- Creating copy of partition table.."
dd if=$DEVICE of=$DIR/disk.table bs=512 count=34

for PARTITION in $(ls $DEVICE?*)
do
  echo "-- Creating copy of $PARTITION partition.."

  TYPE=$(blkid -s TYPE -o value $PARTITION)
  if [ -x /usr/bin/partclone.$TYPE ]
  then
    partclone.$TYPE -c -s $PARTITION | $ARCHIVER -c | split -d -b1G - $DIR/disk/$(basename $PARTITION).$TYPE.$ARCHIVER.
  else
    TYPE=stream
    # workaround because partclone.imager v0.3.12 - image size always zero / segmentation fault
    cat $PARTITION | $ARCHIVER -c | split -d -b1G - $DIR/disk/$(basename $PARTITION).$TYPE.$ARCHIVER.
  fi
done

echo "-- Backup complete."
